/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jrandrews.jsc.polyglot;

import static org.testng.Assert.assertNotNull;

import org.testng.annotations.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
