/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.oracle.jsc.polyglot;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private final Logger log = LoggerFactory.getLogger(this.getClass());

    public String getGreeting() {
        log.debug("getGreeting()");
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
